name: my_site
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  austerity: ^1.1.0
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.1
  path_provider: ^2.0.15
  user_data:
    path: packages/user_data
  flutter_svg: ^2.0.6
  go_router: ^8.1.0
  wolt_responsive_layout_grid: ^0.0.2
  font_awesome_flutter: ^10.4.0
  responsive_toolkit: ^0.0.5
  dropdown_button2: ^2.1.3

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
 
  assets:
    - assets/images/svg/
    - assets/images/png/


flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/png/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#6750A4"
